# Generated by Django 4.0.6 on 2022-07-23 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendingMachine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.FloatField()),
                ('vendingMachine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendingMachine.vendingmachine')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendingMachine.product')),
                ('vendingMachine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendingMachine.vendingmachine')),
            ],
        ),
    ]
