# Generated by Django 4.0.6 on 2022-08-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendingMachine', '0003_rename_address_vendingmachine_located_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendingmachine',
            name='machine_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendingmachine',
            name='payment_method',
            field=models.CharField(max_length=100),
        ),
    ]
