# Generated by Django 4.0.6 on 2022-08-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendingMachine', '0006_alter_product_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='crudMethod/static/image/sample_product_image.png', null=True, upload_to='productImage/'),
        ),
        migrations.AlterField(
            model_name='vendingmachine',
            name='vendMachine_image',
            field=models.ImageField(blank=True, default='crudMethod/static/image/vending_machine.png', null=True, upload_to='vendMachineimage/'),
        ),
    ]
