# Generated by Django 4.0.6 on 2022-08-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendingMachine', '0007_alter_product_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='crudMethod/media/productImage/sample_product_image.png', null=True, upload_to='productImage/'),
        ),
    ]
