# Generated by Django 4.0.6 on 2022-08-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendingMachine', '0008_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='productImage/sample_product_image.png', null=True, upload_to='productImage/'),
        ),
    ]
