# Generated by Django 4.0.6 on 2022-09-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendingMachine', '0009_alter_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendingmachine',
            name='available_product_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendingmachine',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
